version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest

sphinx:
   configuration: docs/conf.py

python:
  version: 3
  system_packages: False
  install:
    - method: pip
      path: .
      extra_requirements:
        - Build-Docs
